[package]
authors = ['JNHua <huajiannan@abmatrix.cn>']
edition = '2018'
name = 'contract-node-wasm'
version = '1.0.0'

[features]
default = []
std = ['contract_node/std']

[workspace]
members = []
[dependencies.contract_node]
default-features = false
path = '..'
[profile.release]
lto = true
panic = 'abort'

[lib]
crate-type = ['cdylib']
