[package]
authors = ['JNHua <huajiannan@abmatrix.cn>']
edition = '2018'
name = 'contract-runtime-wasm'
version = '1.0.0'

[features]
default = []
std = ['contract-runtime/std']

[workspace]
members = []
[dependencies.contract-runtime]
default-features = false
path = '..'
[profile.release]
lto = true
panic = 'abort'

[lib]
crate-type = ['cdylib']
